"""Profile configuration: paths, reading, writing."""

from __future__ import annotations

import shutil
import tomllib
from pathlib import Path

from xtp import toml_writer

# ── Paths ──────────────────────────────────────────────────────────────────

CONFIG_DIR = Path.home() / ".config" / "xtp"
PROFILES_DIR = CONFIG_DIR / "profiles"
GLOBAL_CONFIG = CONFIG_DIR / "config.toml"


def profile_dir(name: str) -> Path:
    return PROFILES_DIR / name


def profile_toml(name: str) -> Path:
    return profile_dir(name) / "profile.toml"


# ── Profile helpers ────────────────────────────────────────────────────────

def list_profiles() -> list[str]:
    """Return sorted list of profile names that have a profile.toml."""
    if not PROFILES_DIR.is_dir():
        return []
    return sorted(
        d.name
        for d in PROFILES_DIR.iterdir()
        if d.is_dir() and (d / "profile.toml").is_file()
    )


def load_profile(name: str) -> dict:
    """Load and return the parsed profile.toml for *name*."""
    path = profile_toml(name)
    if not path.is_file():
        raise FileNotFoundError(f"Profile '{name}' not found at {path}")
    with open(path, "rb") as f:
        return tomllib.load(f)


def save_profile(name: str, data: dict) -> None:
    """Write *data* as TOML to the profile's profile.toml."""
    pdir = profile_dir(name)
    pdir.mkdir(parents=True, exist_ok=True)
    profile_toml(name).write_text(toml_writer.dumps(data))


def ensure_profile_dirs(name: str) -> None:
    """Create the standard subdirectories for a profile."""
    pdir = profile_dir(name)
    (pdir / "claude").mkdir(parents=True, exist_ok=True)
    (pdir / "gh").mkdir(parents=True, exist_ok=True)
    (pdir / "aws").mkdir(parents=True, exist_ok=True)


def seed_claude_config(name: str) -> None:
    """Copy ~/.claude.json into the profile's claude dir to skip onboarding."""
    source = Path.home() / ".claude.json"
    if not source.is_file():
        return
    dest = profile_dir(name) / "claude" / ".claude.json"
    if not dest.exists():
        shutil.copy2(source, dest)


def build_env(name: str) -> dict[str, str]:
    """Build the environment variable dict for a profile."""
    cfg = load_profile(name)
    pdir = profile_dir(name)
    env: dict[str, str] = {}

    # Profile indicator
    env["XTP_PROFILE"] = name
    env["XTP_PROFILE_DIR"] = str(pdir)

    # Claude Code
    env["CLAUDE_CONFIG_DIR"] = str(pdir / "claude")

    # Git identity
    git = cfg.get("git", {})
    if git.get("author_name"):
        env["GIT_AUTHOR_NAME"] = git["author_name"]
        env["GIT_COMMITTER_NAME"] = git["author_name"]
    if git.get("author_email"):
        env["GIT_AUTHOR_EMAIL"] = git["author_email"]
        env["GIT_COMMITTER_EMAIL"] = git["author_email"]
    if git.get("ssh_key"):
        key_path = str(Path(git["ssh_key"]).expanduser())
        env["GIT_SSH_COMMAND"] = f"ssh -i {key_path} -o IdentitiesOnly=yes"

    # GitHub CLI
    env["GH_CONFIG_DIR"] = str(pdir / "gh")

    # Chrome / Browser
    chrome = cfg.get("chrome", {})
    if chrome.get("profile_directory"):
        browser_script = pdir / "browser.sh"
        env["BROWSER"] = str(browser_script)

    # AWS
    aws = cfg.get("aws", {})
    if aws.get("profile"):
        env["AWS_PROFILE"] = aws["profile"]
        aws_dir = pdir / "aws"
        env["AWS_CONFIG_FILE"] = str(aws_dir / "config")
        env["AWS_SHARED_CREDENTIALS_FILE"] = str(aws_dir / "credentials")

    # npm
    npm = cfg.get("npm", {})
    if npm.get("isolate"):
        env["NPM_CONFIG_USERCONFIG"] = str(pdir / "npmrc")

    # Custom env vars
    for key, value in cfg.get("env", {}).items():
        env[key] = str(Path(value).expanduser()) if "~" in str(value) else str(value)

    return env


def generate_browser_script(name: str) -> None:
    """Generate the browser.sh wrapper for a profile's Chrome profile."""
    cfg = load_profile(name)
    chrome = cfg.get("chrome", {})
    profile_directory = chrome.get("profile_directory")
    if not profile_directory:
        return

    pdir = profile_dir(name)
    script = pdir / "browser.sh"
    script.write_text(
        f'#!/bin/bash\n'
        f'# Auto-generated by xtp for profile: {name}\n'
        f'# Opens URLs in Chrome with the correct profile\n'
        f'exec open -na "Google Chrome" --args '
        f'--profile-directory="{profile_directory}" "$@"\n'
    )
    script.chmod(0o755)
